In [2]:
# https://wikidocs.net/52846

---
# 텐서 조작하기 2
---

---
## view - 원소의 수를 유지하면서 텐서의 크기 변경
텐서플로의 reshape과 같은 역할

In [3]:
import numpy as np
import torch

# 임의의 3차원 텐서 만들기
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)

In [4]:
# 쉐잎 확인
print(ft.shape)

# view를 이용해 2차원으로 변경
print(ft.view([-1, 3])) # ft 라는 텐서를 view를 이용해 [-1, 3] 으로 변경 (-1은 알아서 계산되어 들어감)
print(ft.view([-1, 3]).shape)


torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
# 텐서 차원은 유지하되 크기만 바꾸기
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


---
## squeeze - 1인 차원을 제거

In [6]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [7]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


---
## unsqueeze - 특정 위치에 1인 차원을 추가

In [8]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [9]:
# 첫번째 차원에 1인 차원을 추가
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
# view 로도 가능
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
# 두번째 차원에 1인 차원을 추가
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


---
## type casting - 자료형 변환하기

In [12]:
# long 타입 선언
lt = torch.LongTensor([1,2,3,4])
print(lt)

# .float() 붙여 float형으로 변경
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [13]:
# byte타입 선언
bt = torch.ByteTensor([True, False, False, True])
print(bt)

# .long()
print(bt.long())

# .float()
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


---
## 연결하기 concatenate

In [15]:
# 2,2 크기 텐서 만들기
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [17]:
# 첫번째 차원 늘리기
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=0).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


---
## 쌓기 stacking

In [19]:
# 2, 크기의 3개 생성
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [25]:
# 첫번째 차원이 증가하도록 쌓기
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape)

# (2,) 의 크기인데 .unsqueeze(0) 해서 (1,2)로 만든 후 쌓아서 (3,2)로 만듦

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [29]:
# 두번째 차원이 증가하도록 쌓기
print(torch.stack([x,y,z], dim=1))
print(torch.stack([x,y,z], dim=1).shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


---
## 0과 1로 채워진 텐서 - ones-like , zeros-like

In [31]:
# 2,3 크기 텐서 만들기
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [33]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


---
## 덮어쓰기 - ln place operation

In [39]:
# 2,2 크기 텐서 만들기
x = torch.FloatTensor([[1, 2], [3, 4]])

In [36]:
print(x.mul(2.))    # 곱하기 한 값
print(x)            # 기존의 값

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [40]:
# 연산 뒤에 _ 언더바를 붙이면 기존 값을 덮어쓰기 한다
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
