In [ ]:
# https://wikidocs.net/52460

---
# 텐서 조작하기 1
---

In [1]:
import numpy as np

In [2]:
# numpy로 1차원 벡터 만들기
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
# 벡터의 차원과 크기를 출력
# 차원
print('Rank of t:', t.ndim)
# 크기
print('shape of t:', t.shape)

Rank of t: 1
shape of t: (7,)


In [ ]:
# 너무 기초라서 조금 생략

In [ ]:
# 3. 파이토치 텐서 선언하기

In [4]:
import torch

In [6]:
# 1D with pytorch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.,])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
# 텐서의 차원
print(t.dim())

# 텐서의 크기
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [9]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [10]:
# 2D with Pytorch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
# 텐서의 차원
print(t.dim())

# 텐서의 크기
print(t.size())

2
torch.Size([4, 3])


In [ ]:
# 3) 브로드캐스팅
# 크기가 다른 텐서에 대해 사칙 연산을 수행 할 때 브로드캐스팅 이라는 기능을 이용 할 수 있다.

In [12]:
# 우선 크기가 같을 때
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [13]:
# 크기가 다를 때
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

# m2 인 [3] 에 브로드캐스팅이 적용 되어 [3,3]로 바꿔 연산 된다.

tensor([[4., 5.]])


In [15]:
# 2*1 Vector + 1*2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

# m2 : [[3], [4]] >> [[3,3], [4,4]]

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 4) 자주 사용되는 기능들

In [ ]:
# 행렬곱과 그냥 곱셈의 차이
# 행렬곱 : .matmul
# 원소 별 곱셈 : .mul

In [18]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.shape)
print(m1.matmul(m2))

shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [20]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))

shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# 평균 구하기

In [21]:
# 1차원 평균
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [27]:
# 2차원 평균
t = torch.FloatTensor([[1, 2], 
                       [3, 4]])
print(t)

# 4개의 원소에 대한 평균을 반환
print(t.mean())
# 차원을 인자로 줄 경우 (dim=0 , 행을 제거하고 열만 고려)
print(t.mean(dim=0))    # 1,3 의 평균과 2,4 평균을 반환
# 차원을 인자로 줄 경우 (dim=1, 열을 제거하고 행만 고려)
print(t.mean(dim=1))    # 1,2 의 평균과 3,4 평균을 반환
# 차원을 인자로 줄 경우 (dim=-1 , 마지막 차원을 제거 == 열을 제거)
print(t.mean(dim=-1))    # 1,2 의 평균과 3,4 평균을 반환

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
# 덧셈

In [28]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
# 최대와 아그맥스
# max : 원소의 최대값 반환
# agmax : 최대값을 가진 인덱스를 리턴

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [35]:
print(t.max())
print('-'*20)
print(t.max(dim=0)) # 행을 제거하고 열만 고려만 최대값 반환
# max에 dim을 인자로 주면 argmax도 함께 반환함

tensor(4.)
--------------------
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [36]:
# max 또는 argmax만 반환 받고 싶을 때
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [39]:
# dim 인자를 1, -1로 주었을 때
print(t.max(dim=1))
print('-'*20)
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
--------------------
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
