In [2]:
# https://wikidocs.net/60848

---
# 03. XOR 문제 - 단층 퍼셉트론 구현하기

In [3]:
# 라이브러리 불러오고 디바이스 설정
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed(777)


In [4]:
# XOR 문제에 해당되는 데이터 정의
X = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [5]:
# 단층 퍼셉트론을 구현
# 시그모이드를 사용
linear = nn.Linear(2, 1, bias = True)   # 입력2개 출력1개
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)

In [6]:
# 비용 함수와 옵티마이저 정의 
# loss function은 Binary Cross Entropy를 사용
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [7]:
# 10000번의 학습

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
    # loss function
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 100 == 0 :
        print(step, cost.item())

0 0.7273974418640137
100 0.6931475400924683
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [8]:
# 위의 비용을 확인해보면 줄어들지 않음
# 예측까지 해보자

In [9]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('모델의 출력값(Hypothesis):\n', hypothesis.detach().cpu().numpy())
    print('모델의 예측값(Predicted):\n', predicted.detach().cpu().numpy())
    print('실제값(Y):\n', Y.cpu().numpy())
    print('정확도(Accuracy):\n', accuracy.item())

모델의 출력값(Hypothesis):
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
모델의 예측값(Predicted):
 [[0.]
 [0.]
 [0.]
 [0.]]
실제값(Y):
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy):
 0.5


In [10]:
# 문제를 풀지 못하는 것을 확인

In [11]:
###########################################
# hypothesis.detach().cpu().numpy()
# Y.cpu().numpy()
# accuracy.item() 
# 차이