---
# 08. 다층 퍼셉트론으로 MNIST 분류하기

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# 데이터 불러오기
from sklearn.datasets import fetch_openml

In [3]:
mnist = fetch_openml('mnist_784', version=1, cache=True)

In [ ]:
print(type(mnist))
# <class 'sklearn.utils.Bunch'>
print('-'*40)
print(mnist)
# {'data':        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
# 0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# ...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
# 69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
# 69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

#        pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
# 0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
# ...        ...  ...       ...       ...       ...       ...       ...   
# 69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
# 69997      0.0  ...       0.0       0.0       0.0       0.0       0.0
print('-'*40)
print(mnist[0])
# KeyError: 0 -> 안불러짐

In [15]:
print(len(mnist))
print(type(mnist.data))
print(mnist.data)
print(type(mnist.target))
print(mnist.target)

9
<class 'pandas.core.frame.DataFrame'>
       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

In [8]:
mnist2 = fetch_openml('mnist_784', version=1, as_frame=False)

In [ ]:
print(type(mnist2))
# <class 'sklearn.utils.Bunch'>
print('-'*40)
print(mnist2)
# {'data': array([[0., 0., 0., ..., 0., 0., 0.],
#        [0., 0., 0., ..., 0., 0., 0.],
#        [0., 0., 0., ..., 0., 0., 0.],
#        ...,
#        [0., 0., 0., ..., 0., 0., 0.],
#        [0., 0., 0., ..., 0., 0., 0.],
#        [0., 0., 0., ..., 0., 0., 0.]]), 'target': array(['5', '0', '4', ..., '4', '5', '6'], dtype=object), 'frame': None, 'categories': {}, 'feature_names': ['pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6', 'pixel7', 'pixel8', 'pixel9', 'pixel10', 'pixel11', 'pixel12', 'pixel13', 'pixel14', 'pixel15', 'pixel16', 'pixel17', 'pixel18', 'pixel19', 'pixel20', 'pixel21', 'pixel22', 'pixel23', 'pixel24', 'pixel25', 'pixel26', 'pixel27', 'pixel28', 'pixel29', 'pixel30', 'pixel31', 'pixel32', 'pixel33', 'pixel34', 'pixel35', 'pixel36', 'pixel37', 'pixel38', 'pixel39', 'pixel40', 'pixel41', 'pixel42', 'pixel43', 'pixel44', 'pixel45', 'pixel46', 'pixel47', 'pixel48', 'pixel49', 'pixel50', 'pixel51', 'pixel52', 'pixel53', 'pixel54', 'pixel55', 'pixel56', 'pixel57', 'pixel58', 'pixel59', 'pixel60', 'pixel61', 'pixel62', 'pixel63', 'pixel64', 'pixel65', 'pixel66', 'pixel67', 'pixel68', 'pixel69', 
print('-'*40)
print(mnist2[0])
# KeyError: 0 -> 안불러짐

In [16]:
print(len(mnist2))
print(type(mnist2.data))
print(mnist2.data)
print(type(mnist2.target))
print(mnist2.target)


9
<class 'numpy.ndarray'>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<class 'numpy.ndarray'>
['5' '0' '4' ... '4' '5' '6']
