### 1강. 텐서  
https://youtu.be/6SF_qAd99Yg

토치의 텐서는 numpy array와 비슷하다.

In [77]:
# 라이브러리 불러오기
import torch
import numpy as np

### 텐서 만들기
---

In [78]:
# 5,4 크기의 텐서 만들기
x = torch.empty(5,4)
print(x)

tensor([[1.0194e-38, 1.0745e-38, 1.0653e-38, 1.0469e-38],
        [8.7245e-39, 1.0745e-38, 1.0194e-38, 9.6429e-39],
        [9.9184e-39, 5.5103e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 4.1328e-39, 1.0102e-38, 1.0745e-38],
        [4.1328e-39, 4.9592e-39, 9.0918e-39, 4.6837e-39]])


In [79]:
# 1로 채운 텐서 만들기
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [80]:
# 0으로 채운 텐서 만들기
torch.zeros(2)

tensor([0., 0.])

In [81]:
# 랜덤 값으로 텐서 만들기
torch.rand(5,6)

tensor([[0.8744, 0.7456, 0.6841, 0.9217, 0.8476, 0.0053],
        [0.0270, 0.4349, 0.2463, 0.7308, 0.6352, 0.9979],
        [0.0255, 0.7189, 0.6921, 0.7503, 0.9478, 0.9250],
        [0.1799, 0.8316, 0.9696, 0.4956, 0.9517, 0.0986],
        [0.8556, 0.4644, 0.6264, 0.8423, 0.1854, 0.9556]])

### list, array를 텐서로 변환하기
---

In [82]:
# list와 array 생성
l =  [13,4]
r = np.array([4, 56, 7])

In [83]:
torch.tensor(l)

tensor([13,  4])

In [84]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [85]:
# 사이즈 확인하기
x.size()

torch.Size([5, 4])

In [86]:
# 타입 확인하기
type(x)

torch.Tensor

### 텐서로 연산하기
---

In [87]:
# 연산에 사용할 텐서 생성
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.4099, 0.1879],
        [0.7032, 0.2403]])
tensor([[0.5442, 0.6278],
        [0.6010, 0.9378]])


In [88]:
print(x + y)
print(torch.add(x,y))

tensor([[0.9541, 0.8156],
        [1.3043, 1.1780]])
tensor([[0.9541, 0.8156],
        [1.3043, 1.1780]])


In [89]:
print(y.add(x))
# 이 경우는 y 값이 계속 유지가 된다.
print(y)

tensor([[0.9541, 0.8156],
        [1.3043, 1.1780]])
tensor([[0.5442, 0.6278],
        [0.6010, 0.9378]])


In [90]:
y.add_(x)
# 이렇게 _를 넣으면 replace하여 y+x 한 값을 y로 대체한다.
print(y)

tensor([[0.9541, 0.8156],
        [1.3043, 1.1780]])


### 인덱싱
---

In [91]:
print(y[1,1])
print(y[:1])

tensor(1.1780)
tensor([[0.9541, 0.8156]])


In [92]:
# view 사용하기
# 조금 큰 텐서 생성
x = torch.rand(8,8)
print(x)

tensor([[0.4240, 0.6559, 0.2077, 0.4444, 0.2472, 0.3299, 0.2845, 0.2184],
        [0.9672, 0.4555, 0.7161, 0.5054, 0.8513, 0.1385, 0.9200, 0.5050],
        [0.4277, 0.1667, 0.6338, 0.2358, 0.2072, 0.5400, 0.7947, 0.9137],
        [0.0177, 0.5114, 0.1768, 0.6483, 0.7898, 0.3753, 0.3020, 0.2973],
        [0.7972, 0.7040, 0.5214, 0.0258, 0.7049, 0.2571, 0.5117, 0.3540],
        [0.9580, 0.8907, 0.6664, 0.6618, 0.2466, 0.4488, 0.6059, 0.5156],
        [0.8125, 0.9883, 0.3278, 0.2607, 0.0950, 0.5452, 0.4817, 0.7075],
        [0.0582, 0.0671, 0.0056, 0.7677, 0.4985, 0.6044, 0.0770, 0.2661]])


In [93]:
x.view(64)

tensor([0.4240, 0.6559, 0.2077, 0.4444, 0.2472, 0.3299, 0.2845, 0.2184, 0.9672,
        0.4555, 0.7161, 0.5054, 0.8513, 0.1385, 0.9200, 0.5050, 0.4277, 0.1667,
        0.6338, 0.2358, 0.2072, 0.5400, 0.7947, 0.9137, 0.0177, 0.5114, 0.1768,
        0.6483, 0.7898, 0.3753, 0.3020, 0.2973, 0.7972, 0.7040, 0.5214, 0.0258,
        0.7049, 0.2571, 0.5117, 0.3540, 0.9580, 0.8907, 0.6664, 0.6618, 0.2466,
        0.4488, 0.6059, 0.5156, 0.8125, 0.9883, 0.3278, 0.2607, 0.0950, 0.5452,
        0.4817, 0.7075, 0.0582, 0.0671, 0.0056, 0.7677, 0.4985, 0.6044, 0.0770,
        0.2661])

In [94]:
print(x.size())
print(x.view(64).size())
print(x.view(4, 16).size())
# -1을 사용하면, 고정된 16이라는 값에 맞춰 -1에 값이 자동으로 들어간다.
print(x.view(-1, 16).size())
print(x.view(-1, 4, 4).size())
# 이 view는 cnn 모델에서 마지막 단 FC layer에서 이미지를 한줄로 이어붙여 넘길 때 자주 사용한다.

torch.Size([8, 8])
torch.Size([64])
torch.Size([4, 16])
torch.Size([4, 16])
torch.Size([4, 4, 4])


### tensor에서 numpy 넘어가기
---

In [95]:
y = torch.tensor(y)
print(type(y))

y = y.numpy()
print(type(y))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


C:\Users\lemon\anaconda3\envs\chch\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


### tensor 가 scalar 형태일 때 item 사용하기
---

In [96]:
x = torch.ones(1)

In [97]:
x

tensor([1.])

In [98]:
# 정수나 실수 값 하나로 나오게
x.item()
# tensor 형태로 나온 로스 값을 변환 할 때 자주 사용한다.

1.0