## 2강 역전파
미분 자동으로 계산하기

In [24]:
import torch

In [25]:
# requires_grad를 True로 한다. 디폴트는 False
# requires_grad : x에 관한 연산을 추적할 수 있게하여 미분할 때 사용하게 한다.
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [26]:
# x에 대한 y식을 만든다.
y = x+1
print(y)
# rad_fn=<AddBackward0> 을 확인

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [27]:
# 또 다른 식을 만든다
# 딥러닝에서는 loss 를 구하는 것으로 생각하면 쉽다.
z = 2 * y**2
result = z.mean()
print(result)

tensor(8., grad_fn=<MeanBackward0>)


In [28]:
# 이렇게 나온 결과인 result(=loss)를 기준으로 해서 미분을 진행하자
# d(res)/dx_i = x_i + 1
# res = (z_1 + z_2 + .. + z_4)/4
# z_i = 2y_i ** 2
# z_i = 2(x_i+1)**2

In [29]:
# 실제 계산을 해보자. 역전파 계산을 한다
result.backward()

In [30]:
# x에 대한 미분값이 보고싶을 때
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
